name: deepcpg
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - zsh
    - pytorch
    - torchvision
    - cudatoolkit=10.0
    - pandas
    - matplotlib
    - scipy
    - seaborn
    - snakemake
